<!--NAVIGATION-->
< [Control Structures](2.3-Control_Structures.ipynb) | [Contents](0-Index.ipynb) | [NumPy_Library](3-NumPy_Library.ipynb) >

# 2 Conceitos básicos de programação
## 2.4 Funções

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](http://colab.research.google.com/github/computational-chemical-biology/DataScience/blob/master/2.4-Functions.ipynb)

 <a id="top"></a> <br>
**Conteúdo do *Notebook***
1. [Funções](#1)
    1. [Executando funções](#11)
    1. [Definindo uma função](#12)
    1. [Funções *lambda*](#13)
1. [Entrada e saída de arquivos (I/O)](#2)
    1. [Escrever dados para um arquivo](#21)
    1. [Ler dados de um arquivo](#22)
1. [Bibliotecas](#3)
    1. [Bibliotecas nativas](#31)
    1. [Bibliotecas externas](#32)    
1. [Programação Orientada a Objetos](#4)
1. [Referências](#5)

<a id="1"></a> <br>
# 1 - Funções

<a id="11"></a> <br>
## 1.1 - Executando funcões

Previamente utilizamos funções nativas (*built-in*) para facilitar a programação. Função é um bloco de código com parâmetros de entrada (e opcionalmente retornando repostas) para propósitos específicos <cite data-cite="236589/5T4T73QM"></cite>. Em Python uma função é executada da seguinte maneira:

```python
>> saida = função(parâmetros)
```

Por exemplo:

In [1]:
range(5)

range(0, 5)

Em Python 3 se retorna o tipo `iterator` para a função 'range', para visualizar a saída podemos converter em uma lista:

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

Outro exemplo:

In [3]:
abs(-3.5)

3.5

Em muitos casos uma função pode receber múltiplos parâmetros, por exemplo:

In [4]:
# Para saber como a função 'range'
# funciona especificamente
# range?
list(range(5, 0, -1))

[5, 4, 3, 2, 1]

Outro exemplo, ordernar um dicionário:

In [5]:
d = {'a': 100, 'c': 50, 'b': 70}
sorted(d)

['a', 'b', 'c']

In [6]:
d

{'a': 100, 'c': 50, 'b': 70}

In [7]:
d['a']

100

In [8]:
# Veremos o significado de lambda abaixo
sorted(d, key=lambda k: d[k])

['c', 'b', 'a']

<a id="12"></a> <br>
## 1.2 - Definindo uma função

Além das funções nativas (*built-in*), podemos definir funções para executar operações específicas. A estrutura básica de uma função em Python tem a seguinte estrutura

```python
def nome_da_funcao(parametro_1, parametro_2, parametro_3, ...):
    ##########################
    # Execute operações aqui #
    ##########################
    
    return saida
```

\* *`return output` NÃO é estritamente necessário*

No primeiro exemplo utilizamos uma função nativa, `sum`, para somar os números de uma lista e retornar a soma.

In [9]:
def minha_soma(lista_de_numeros):
    return sum(lista_de_numeros)

In [10]:
minha_soma(range(5))

10

Uma função um pouco mais detalhada, sem utilizar uma função nativa:

In [11]:
def soma_em_loop(lista):
    soma = lista[0]
    for item in lista[1:]:
        soma += item
    return soma

In [12]:
soma_em_loop(range(5))

10

Voltando ao problema da seção anterior, vamos ordenar as chaves de um dicionário utilizando uma função customizada ao invés da função `lambda`.

In [13]:
d

{'a': 100, 'c': 50, 'b': 70}

In [14]:
def minha_chave(chave):
    return d[chave]

In [15]:
sorted(d, key=minha_chave)

['c', 'b', 'a']

Veja abaixo por que em algumas circuntâncias utilizar a função `lambda` é conveniente.

<a id="13"></a> <br>
## 1.3 - Funcões *lambda* 

Funções *lambda* são simplesmente funções, com o detalhe de serem anônimas. Resumidamente, pode se utilizar funções regulares para executar as tarefas das funções *lambda*, entretanto, estas são úteis por serem simples e eficientes.

O exemplo abaixo é um exemplo de aplicação da função `lambda`:

In [16]:
sorted(d, key=lambda k: d[k])

['c', 'b', 'a']

Existe apenas uma expressão dentro da função `lambda`. Neste caso a entrada é `k`, uma chave dentro do dicionário `d` e de saída `d[k]` (o valor do dicionário correspondente à chave `k`). Logo, as chaves do dicionário são ordenadas pelos valores.

<a id="2"></a> <br>
# Entrada e saída de arquivos (I/O)

Nas próximas seções veremos bibliotecas que possuem funções sofisticadas para ler e escrever arquivos, aqui veremos funções nativas que são simples e eficientes para muitas aplicações.

<a id="21"></a> <br>
## 2.1 - Escrever dados para um arquivo

In [17]:
f = open("arquivo_1.csv", "w") # a função open cria um manipulador de arquivos (handler),
                               # que é atribuído para a variável f, 
                               # enquanto "w" é o parâmetro que indica o modo (w para write)
for item in range(6):
    f.write(str(item)) # escreve o número para o arquivo
    # adicione uma caractere que faz com que o arquivo mude de linha
    f.write("\n") 
    # alternativamente podemos fazer:
    # f.write(str(item)+"\n") # como vimos anteriormente `+` concatena caracteres
f.close() # fecha o manipulador de arquivos por motivos de segurança

inspecione o arquivo `arquivo_1.csv` criado

In [18]:
!cat arquivo_1.csv

0
1
2
3
4
5


Note que houve uma conversão de `int` para `str`.

Uma outra opção nativa para escrever arquivos:

In [19]:
with open("arquivo_2.csv", "w") as f: # a função with se encarrega de abrir e fechar o manipulador de arquivos
    for item in range(4):
        f.write(str(item))
        f.write("\n") 

In [20]:
!cat arquivo_2.csv

0
1
2
3


Quando necessário _adicionar novos elementos_ ao invés de _sobrescrever_ arquivos existentes. Neste caso podemos usar o parâmetro `a` para o modo adicionar na função `open`:

In [21]:
with open("arquivo_2.csv", "a") as f:
    for item in range(15, 19):
        f.write(str(item)+"\n")

In [22]:
!cat arquivo_2.csv

0
1
2
3
15
16
17
18


<a id="22"></a> <br>
## 2.2 - Ler dados de um arquivo

Para ler texto de um arquivo pode se usar o parâmetro `r`  (para _read_) como o modo.

In [23]:
f = open("arquivo_1.csv", "r") # modo leitura
conteudo = [item for item in f] # lembra se do list comprehension? Se não, volte a seção anterior
print(conteudo)

['0\n', '1\n', '2\n', '3\n', '4\n', '5\n']


Usualmente se remove o caractere 'nova linha' (*newline*)

In [24]:
conteudo = [item.strip("\n") for item in conteudo] # usando função strip um método de caracteres em Python
print(conteudo)

['0', '1', '2', '3', '4', '5']


Uma outra alternativa é a função `map` que muda o 'tipo' de variáveis em uma lista

In [25]:
valores_numericos = list(map(int, conteudo)) # use map para converter caracteres em números inteiros
print(valores_numericos)
f.close() # temos que fechar o manipulador de arquivos depois de lermos

[0, 1, 2, 3, 4, 5]


Podemos também usar a função `with` para ler um arquivo:

In [26]:
with open("arquivo_2.csv", "r") as f:
    conteudo = [item for item in f] 
    conteudo = [item.strip("\n") for item in conteudo]
    print('Antes de converte para `int`')
    print(conteudo)
    valores_inteiros = list(map(int, conteudo))
    print('Depois ...')
    print(valores_inteiros)

Antes de converte para `int`
['0', '1', '2', '3', '15', '16', '17', '18']
Depois ...
[0, 1, 2, 3, 15, 16, 17, 18]


In [27]:
# se lembra como remover os arquivos criados?

<a id="3"></a> <br>
# 3 - Bibliotecas

Frequentemente necessitamos realizar tarefas complexas e podemos utilizar código desenvolvido préviamente e disponível como bibliotecas (*libraries*) externas.

<a id="31"></a> <br>
## 3.1 - Bibliotecas nativas

Python fornece muitas bibliotecas nativas (*built-in*) para executar algumas tarefas comuns de utilidade geral.

Como exemplo a biblioteca __math__ pode ser importada com:

In [28]:
import math # use o comando import para carregar a biblioteca

Para usar funções disponíveis na biblioteca, faça: `nome_da_biblioteca.nome_da_funcao`. Por exemplo, quando queremos calcular o logaritmo usando uma função da biblioteca `math`, utilizamos `math.log`

In [29]:
x = 3
print("e^x = e^3 = %f" % math.exp(x)) # potência de 3
print("log(x) = log(3) = %f" % math.log(x)) # logaritimo de 3

e^x = e^3 = 20.085537
log(x) = log(3) = 1.098612


Também é possível importar uma função específica

In [30]:
from math import exp # Importe a função exponencial da biblioteca math
print(exp(x)) # Use a função sem mencionar o nome da biblioteca

20.085536923187668


Ou importe todas as funções de uma biblioteca:

In [31]:
from math import * # Importe todas as funções

In [32]:
print(exp(x))
print(log(x)) # Tentar executar uma função antes de importa la gera erros

20.085536923187668
1.0986122886681098


<a id="32"></a> <br>
## 3.1 - Bibliotecas externas

Python é uma das linguagens de programação mais populares da atualidade, e como tal conta com um número muito grande de bibliotecas para executar um amplo número de tarefas. É importante pesquisar bem antes de começar a desenvolver para saber se já não existe uma biblioteca para executar a tarefa desejada. 

Usaremos como exemplo inicial a biblioteca __numpy__, que veremos em mais detalhe a frente (__scipy__, __matplotlib__, e __pandas__ também  serão utilizadas em próximas seções).

A instalação de bibliotecas em Python é facilitada pela ferramenta linha de comando <a href="https://packaging.python.org/installing/" target="_blank">pip</a>. Podemos instalar um ou mais pacotes com o seguinte comando

```bash
~$ pip install numpy scipy pandas
```

Carregar bibliotecas externas é realizado da mesma forma que as nativas. Podemos ainda usar _alias_ para atribuir um nome mais curto às bibliotecas, fazendo: `import nome_longo_da_biblioteca as nome_curto`

In [33]:
# Depois de instalada a biblioteca numpy pode ser importada
import numpy as np # depois de importada usaremos np para executar as funções

In [34]:
x = np.array([[1,2,3], [4,5,7]], dtype=np.float) # crie um objecto numpy to tipo array (vetor ou matriz),
                                                 # especificando o tipo de dados com float (fração)
print(x)
print(type(x))

[[1. 2. 3.]
 [4. 5. 7.]]
<class 'numpy.ndarray'>


Podemos usar o atributo `shape` presente na 'classe' `numpy.ndarray` para checar as dimensões da matriz

In [35]:
x.shape

(2, 3)

Diferentemente do tipo `list`, temos que ter todos os elementos em um `array` do mesmo tipo

In [36]:
y = np.array([1, 'yes'])
y

array(['1', 'yes'], dtype='<U21')

In [37]:
y[0], type(y[0])

('1', numpy.str_)

In [38]:
y_list = [1, 'yes']
y_list[0], type(y_list[0])

(1, int)

As bibliotecas __Scipy/Numpy__ fornecem um grande número de funcionalidades para manipulação númerica.

In [39]:
from scipy.stats import pearsonr, spearmanr # funçãoes para correlação

In [40]:
print(pearsonr(x[1, :], x[0, :]))
print(spearmanr(x[1, :], x[0, :]))

(0.9819805060619659, 0.1210377183236763)
SpearmanrResult(correlation=1.0, pvalue=0.0)


__Pandas__ (`Python Data Analysis Library`) é uma excelente biblioteca para manipular estruturas do tipo `DataFrame` como veremos adiante

In [41]:
import pandas as pd

In [42]:
x

array([[1., 2., 3.],
       [4., 5., 7.]])

In [43]:
x_df = pd.DataFrame(x)
x_df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  7.0

Como discutido anteriormente, `pandas` também implementa métodos simples e transparentes para importar e exportar dados:

In [44]:
x_df.to_csv('tmp_pd.csv', index=False) # parâmetro `index=False`: exclui uma coluna com índices para as linhas

In [45]:
df = pd.read_csv('tmp_pd.csv')

In [46]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  7.0

<a id="4"></a> <br>
# 4 - Programação Orientada a Objetos

Em programação, a orientação a objetos é uma maneira de isolar dados e métodos específicos para processar estes dados em *Objetos*.

Objetos são um encapsulamento de variáveis e funções em uma única entidade. Os objetos têm suas variáveis e funções geradas por classes (`class`). Classes são essencialmente um molde para criar objetos.

In [47]:
# exemplo de uma classe
class Pessoa:
    departamento = 'Escola de Ciências Farmacêuticas' # uma variável da classe

    def set_nome(self, novo_name): # um método ou funcão
        self.nome = novo_name
    def set_localizacao(self, nova_localizacao):
        self.localizacao = nova_localizacao

In [48]:
pessoa = Pessoa() # cria um objeto da classe Pessoa
# cria o valor para o objeto
pessoa.set_nome('Paulo')
pessoa.set_localizacao('Araraquara')
# Acessando variáveis do objeto
print('{} vive em {} e trabalha na {}'.format(pessoa.nome, pessoa.localizacao, pessoa.departamento))

Paulo vive em Araraquara e trabalha na Escola de Ciências Farmacêuticas


Em Python os tipos e estruturas que vimos anteriormente números, caracteres, listas, são todos objetos. Recorde, que estes objetos tem métodos associados como por exemplo:

In [49]:
x = 'Python'
x.upper()

'PYTHON'

Embora orientação a objetos esteja fora do escopo deste curso, uma intuição deste conceito é importante para futuras referências.

<a id="5"></a> <br>
# 5 - Referências
<div class="cite2c-biblio"></div>

###### [Volte ao topo](#top)

<!--NAVIGATION-->
< [Control Structures](2.3-Control_Structures.ipynb) | [Contents](0-Index.ipynb) | [NumPy_Library](3-NumPy_Library.ipynb) >